version: "3"

volumes:
  node_modules:
services:
  my-app-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/src
      - node_modules:/src/node_modules

# https://markus.oberlehner.net/blog/running-nuxt-3-in-a-docker-container/
# he wanted to use: docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build
# but it only worked with: docker compose -f docker-compose.dev.yml up --build
# .. Because I can run two containers that utilize the same port?