version: "3.8"

services:
  my-app:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: simple-todo-container


# https://markus.oberlehner.net/blog/running-nuxt-3-in-a-docker-container/